// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: warp.proto

// Warpinator transfer service (Linux Mint), faithful subset for a krokodyl
// RECEIVE adapter. Canonical source: linuxmint/warpinator (warp.proto).
// Generate Go stubs with the runbook in .claude/spikes/warpinator-runbook.md;
// this file is committed so codegen + validation can happen on a dev machine.

package warppb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LookupName struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ReadableName  string                 `protobuf:"bytes,2,opt,name=readable_name,json=readableName,proto3" json:"readable_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupName) Reset() {
	*x = LookupName{}
	mi := &file_warp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupName) ProtoMessage() {}

func (x *LookupName) ProtoReflect() protoreflect.Message {
	mi := &file_warp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupName.ProtoReflect.Descriptor instead.
func (*LookupName) Descriptor() ([]byte, []int) {
	return file_warp_proto_rawDescGZIP(), []int{0}
}

func (x *LookupName) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LookupName) GetReadableName() string {
	if x != nil {
		return x.ReadableName
	}
	return ""
}

type HaveDuplicate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      bool                   `protobuf:"varint,1,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HaveDuplicate) Reset() {
	*x = HaveDuplicate{}
	mi := &file_warp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HaveDuplicate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HaveDuplicate) ProtoMessage() {}

func (x *HaveDuplicate) ProtoReflect() protoreflect.Message {
	mi := &file_warp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HaveDuplicate.ProtoReflect.Descriptor instead.
func (*HaveDuplicate) Descriptor() ([]byte, []int) {
	return file_warp_proto_rawDescGZIP(), []int{1}
}

func (x *HaveDuplicate) GetResponse() bool {
	if x != nil {
		return x.Response
	}
	return false
}

type RemoteMachineInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DisplayName   string                 `protobuf:"bytes,1,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	UserName      string                 `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoteMachineInfo) Reset() {
	*x = RemoteMachineInfo{}
	mi := &file_warp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteMachineInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteMachineInfo) ProtoMessage() {}

func (x *RemoteMachineInfo) ProtoReflect() protoreflect.Message {
	mi := &file_warp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteMachineInfo.ProtoReflect.Descriptor instead.
func (*RemoteMachineInfo) Descriptor() ([]byte, []int) {
	return file_warp_proto_rawDescGZIP(), []int{2}
}

func (x *RemoteMachineInfo) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *RemoteMachineInfo) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

type RemoteMachineAvatar struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AvatarChunk   []byte                 `protobuf:"bytes,1,opt,name=avatar_chunk,json=avatarChunk,proto3" json:"avatar_chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoteMachineAvatar) Reset() {
	*x = RemoteMachineAvatar{}
	mi := &file_warp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteMachineAvatar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteMachineAvatar) ProtoMessage() {}

func (x *RemoteMachineAvatar) ProtoReflect() protoreflect.Message {
	mi := &file_warp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteMachineAvatar.ProtoReflect.Descriptor instead.
func (*RemoteMachineAvatar) Descriptor() ([]byte, []int) {
	return file_warp_proto_rawDescGZIP(), []int{3}
}

func (x *RemoteMachineAvatar) GetAvatarChunk() []byte {
	if x != nil {
		return x.AvatarChunk
	}
	return nil
}

type OpInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ident         string                 `protobuf:"bytes,1,opt,name=ident,proto3" json:"ident,omitempty"`
	Timestamp     uint64                 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ReadableName  string                 `protobuf:"bytes,3,opt,name=readable_name,json=readableName,proto3" json:"readable_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpInfo) Reset() {
	*x = OpInfo{}
	mi := &file_warp_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpInfo) ProtoMessage() {}

func (x *OpInfo) ProtoReflect() protoreflect.Message {
	mi := &file_warp_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpInfo.ProtoReflect.Descriptor instead.
func (*OpInfo) Descriptor() ([]byte, []int) {
	return file_warp_proto_rawDescGZIP(), []int{4}
}

func (x *OpInfo) GetIdent() string {
	if x != nil {
		return x.Ident
	}
	return ""
}

func (x *OpInfo) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *OpInfo) GetReadableName() string {
	if x != nil {
		return x.ReadableName
	}
	return ""
}

type TransferOpRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Info            *OpInfo                `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	SenderName      string                 `protobuf:"bytes,2,opt,name=sender_name,json=senderName,proto3" json:"sender_name,omitempty"`
	Receiver        string                 `protobuf:"bytes,3,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Size            uint64                 `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	Count           uint64                 `protobuf:"varint,5,opt,name=count,proto3" json:"count,omitempty"`
	NameIfSingle    string                 `protobuf:"bytes,6,opt,name=name_if_single,json=nameIfSingle,proto3" json:"name_if_single,omitempty"`
	MimeIfSingle    string                 `protobuf:"bytes,7,opt,name=mime_if_single,json=mimeIfSingle,proto3" json:"mime_if_single,omitempty"`
	TopDirBasenames []string               `protobuf:"bytes,8,rep,name=top_dir_basenames,json=topDirBasenames,proto3" json:"top_dir_basenames,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TransferOpRequest) Reset() {
	*x = TransferOpRequest{}
	mi := &file_warp_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferOpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferOpRequest) ProtoMessage() {}

func (x *TransferOpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_warp_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferOpRequest.ProtoReflect.Descriptor instead.
func (*TransferOpRequest) Descriptor() ([]byte, []int) {
	return file_warp_proto_rawDescGZIP(), []int{5}
}

func (x *TransferOpRequest) GetInfo() *OpInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *TransferOpRequest) GetSenderName() string {
	if x != nil {
		return x.SenderName
	}
	return ""
}

func (x *TransferOpRequest) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

func (x *TransferOpRequest) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *TransferOpRequest) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *TransferOpRequest) GetNameIfSingle() string {
	if x != nil {
		return x.NameIfSingle
	}
	return ""
}

func (x *TransferOpRequest) GetMimeIfSingle() string {
	if x != nil {
		return x.MimeIfSingle
	}
	return ""
}

func (x *TransferOpRequest) GetTopDirBasenames() []string {
	if x != nil {
		return x.TopDirBasenames
	}
	return nil
}

type FileChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RelativePath  string                 `protobuf:"bytes,1,opt,name=relative_path,json=relativePath,proto3" json:"relative_path,omitempty"`
	FileType      uint32                 `protobuf:"varint,2,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"`
	Chunk         []byte                 `protobuf:"bytes,3,opt,name=chunk,proto3" json:"chunk,omitempty"`
	FileMode      uint32                 `protobuf:"varint,4,opt,name=file_mode,json=fileMode,proto3" json:"file_mode,omitempty"`
	Time          uint64                 `protobuf:"varint,5,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileChunk) Reset() {
	*x = FileChunk{}
	mi := &file_warp_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChunk) ProtoMessage() {}

func (x *FileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_warp_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChunk.ProtoReflect.Descriptor instead.
func (*FileChunk) Descriptor() ([]byte, []int) {
	return file_warp_proto_rawDescGZIP(), []int{6}
}

func (x *FileChunk) GetRelativePath() string {
	if x != nil {
		return x.RelativePath
	}
	return ""
}

func (x *FileChunk) GetFileType() uint32 {
	if x != nil {
		return x.FileType
	}
	return 0
}

func (x *FileChunk) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

func (x *FileChunk) GetFileMode() uint32 {
	if x != nil {
		return x.FileMode
	}
	return 0
}

func (x *FileChunk) GetTime() uint64 {
	if x != nil {
		return x.Time
	}
	return 0
}

type StopInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *OpInfo                `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	Error         bool                   `protobuf:"varint,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopInfo) Reset() {
	*x = StopInfo{}
	mi := &file_warp_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopInfo) ProtoMessage() {}

func (x *StopInfo) ProtoReflect() protoreflect.Message {
	mi := &file_warp_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopInfo.ProtoReflect.Descriptor instead.
func (*StopInfo) Descriptor() ([]byte, []int) {
	return file_warp_proto_rawDescGZIP(), []int{7}
}

func (x *StopInfo) GetInfo() *OpInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *StopInfo) GetError() bool {
	if x != nil {
		return x.Error
	}
	return false
}

type VoidType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoidType) Reset() {
	*x = VoidType{}
	mi := &file_warp_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoidType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoidType) ProtoMessage() {}

func (x *VoidType) ProtoReflect() protoreflect.Message {
	mi := &file_warp_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoidType.ProtoReflect.Descriptor instead.
func (*VoidType) Descriptor() ([]byte, []int) {
	return file_warp_proto_rawDescGZIP(), []int{8}
}

var File_warp_proto protoreflect.FileDescriptor

const file_warp_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"warp.proto\x12\x04warp\"A\n" +
	"\n" +
	"LookupName\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rreadable_name\x18\x02 \x01(\tR\freadableName\"+\n" +
	"\rHaveDuplicate\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\bR\bresponse\"S\n" +
	"\x11RemoteMachineInfo\x12!\n" +
	"\fdisplay_name\x18\x01 \x01(\tR\vdisplayName\x12\x1b\n" +
	"\tuser_name\x18\x02 \x01(\tR\buserName\"8\n" +
	"\x13RemoteMachineAvatar\x12!\n" +
	"\favatar_chunk\x18\x01 \x01(\fR\vavatarChunk\"a\n" +
	"\x06OpInfo\x12\x14\n" +
	"\x05ident\x18\x01 \x01(\tR\x05ident\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x04R\ttimestamp\x12#\n" +
	"\rreadable_name\x18\x03 \x01(\tR\freadableName\"\x94\x02\n" +
	"\x11TransferOpRequest\x12 \n" +
	"\x04info\x18\x01 \x01(\v2\f.warp.OpInfoR\x04info\x12\x1f\n" +
	"\vsender_name\x18\x02 \x01(\tR\n" +
	"senderName\x12\x1a\n" +
	"\breceiver\x18\x03 \x01(\tR\breceiver\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x04R\x04size\x12\x14\n" +
	"\x05count\x18\x05 \x01(\x04R\x05count\x12$\n" +
	"\x0ename_if_single\x18\x06 \x01(\tR\fnameIfSingle\x12$\n" +
	"\x0emime_if_single\x18\a \x01(\tR\fmimeIfSingle\x12*\n" +
	"\x11top_dir_basenames\x18\b \x03(\tR\x0ftopDirBasenames\"\x94\x01\n" +
	"\tFileChunk\x12#\n" +
	"\rrelative_path\x18\x01 \x01(\tR\frelativePath\x12\x1b\n" +
	"\tfile_type\x18\x02 \x01(\rR\bfileType\x12\x14\n" +
	"\x05chunk\x18\x03 \x01(\fR\x05chunk\x12\x1b\n" +
	"\tfile_mode\x18\x04 \x01(\rR\bfileMode\x12\x12\n" +
	"\x04time\x18\x05 \x01(\x04R\x04time\"B\n" +
	"\bStopInfo\x12 \n" +
	"\x04info\x18\x01 \x01(\v2\f.warp.OpInfoR\x04info\x12\x14\n" +
	"\x05error\x18\x02 \x01(\bR\x05error\"\n" +
	"\n" +
	"\bVoidType2\xed\x03\n" +
	"\x04Warp\x12A\n" +
	"\x16CheckDuplicateTransfer\x12\x10.warp.LookupName\x1a\x13.warp.HaveDuplicate\"\x00\x12C\n" +
	"\x14GetRemoteMachineInfo\x12\x10.warp.LookupName\x1a\x17.warp.RemoteMachineInfo\"\x00\x12I\n" +
	"\x16GetRemoteMachineAvatar\x12\x10.warp.LookupName\x1a\x19.warp.RemoteMachineAvatar\"\x000\x01\x12E\n" +
	"\x18ProcessTransferOpRequest\x12\x17.warp.TransferOpRequest\x1a\x0e.warp.VoidType\"\x00\x122\n" +
	"\rStartTransfer\x12\f.warp.OpInfo\x1a\x0f.warp.FileChunk\"\x000\x01\x129\n" +
	"\x17CancelTransferOpRequest\x12\f.warp.OpInfo\x1a\x0e.warp.VoidType\"\x00\x120\n" +
	"\fStopTransfer\x12\x0e.warp.StopInfo\x1a\x0e.warp.VoidType\"\x00\x12*\n" +
	"\x04Ping\x12\x10.warp.LookupName\x1a\x0e.warp.VoidType\"\x00B\x1cZ\x1akrokodyl/warpinator/warppbb\x06proto3"

var (
	file_warp_proto_rawDescOnce sync.Once
	file_warp_proto_rawDescData []byte
)

func file_warp_proto_rawDescGZIP() []byte {
	file_warp_proto_rawDescOnce.Do(func() {
		file_warp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_warp_proto_rawDesc), len(file_warp_proto_rawDesc)))
	})
	return file_warp_proto_rawDescData
}

var file_warp_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_warp_proto_goTypes = []any{
	(*LookupName)(nil),          // 0: warp.LookupName
	(*HaveDuplicate)(nil),       // 1: warp.HaveDuplicate
	(*RemoteMachineInfo)(nil),   // 2: warp.RemoteMachineInfo
	(*RemoteMachineAvatar)(nil), // 3: warp.RemoteMachineAvatar
	(*OpInfo)(nil),              // 4: warp.OpInfo
	(*TransferOpRequest)(nil),   // 5: warp.TransferOpRequest
	(*FileChunk)(nil),           // 6: warp.FileChunk
	(*StopInfo)(nil),            // 7: warp.StopInfo
	(*VoidType)(nil),            // 8: warp.VoidType
}
var file_warp_proto_depIdxs = []int32{
	4,  // 0: warp.TransferOpRequest.info:type_name -> warp.OpInfo
	4,  // 1: warp.StopInfo.info:type_name -> warp.OpInfo
	0,  // 2: warp.Warp.CheckDuplicateTransfer:input_type -> warp.LookupName
	0,  // 3: warp.Warp.GetRemoteMachineInfo:input_type -> warp.LookupName
	0,  // 4: warp.Warp.GetRemoteMachineAvatar:input_type -> warp.LookupName
	5,  // 5: warp.Warp.ProcessTransferOpRequest:input_type -> warp.TransferOpRequest
	4,  // 6: warp.Warp.StartTransfer:input_type -> warp.OpInfo
	4,  // 7: warp.Warp.CancelTransferOpRequest:input_type -> warp.OpInfo
	7,  // 8: warp.Warp.StopTransfer:input_type -> warp.StopInfo
	0,  // 9: warp.Warp.Ping:input_type -> warp.LookupName
	1,  // 10: warp.Warp.CheckDuplicateTransfer:output_type -> warp.HaveDuplicate
	2,  // 11: warp.Warp.GetRemoteMachineInfo:output_type -> warp.RemoteMachineInfo
	3,  // 12: warp.Warp.GetRemoteMachineAvatar:output_type -> warp.RemoteMachineAvatar
	8,  // 13: warp.Warp.ProcessTransferOpRequest:output_type -> warp.VoidType
	6,  // 14: warp.Warp.StartTransfer:output_type -> warp.FileChunk
	8,  // 15: warp.Warp.CancelTransferOpRequest:output_type -> warp.VoidType
	8,  // 16: warp.Warp.StopTransfer:output_type -> warp.VoidType
	8,  // 17: warp.Warp.Ping:output_type -> warp.VoidType
	10, // [10:18] is the sub-list for method output_type
	2,  // [2:10] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_warp_proto_init() }
func file_warp_proto_init() {
	if File_warp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_warp_proto_rawDesc), len(file_warp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_warp_proto_goTypes,
		DependencyIndexes: file_warp_proto_depIdxs,
		MessageInfos:      file_warp_proto_msgTypes,
	}.Build()
	File_warp_proto = out.File
	file_warp_proto_goTypes = nil
	file_warp_proto_depIdxs = nil
}
