// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: warp.proto

// Warpinator transfer service (Linux Mint), faithful subset for a krokodyl
// RECEIVE adapter. Canonical source: linuxmint/warpinator (warp.proto).
// Generate Go stubs with the runbook in .claude/spikes/warpinator-runbook.md;
// this file is committed so codegen + validation can happen on a dev machine.

package warppb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Warp_CheckDuplicateTransfer_FullMethodName   = "/warp.Warp/CheckDuplicateTransfer"
	Warp_GetRemoteMachineInfo_FullMethodName     = "/warp.Warp/GetRemoteMachineInfo"
	Warp_GetRemoteMachineAvatar_FullMethodName   = "/warp.Warp/GetRemoteMachineAvatar"
	Warp_ProcessTransferOpRequest_FullMethodName = "/warp.Warp/ProcessTransferOpRequest"
	Warp_StartTransfer_FullMethodName            = "/warp.Warp/StartTransfer"
	Warp_CancelTransferOpRequest_FullMethodName  = "/warp.Warp/CancelTransferOpRequest"
	Warp_StopTransfer_FullMethodName             = "/warp.Warp/StopTransfer"
	Warp_Ping_FullMethodName                     = "/warp.Warp/Ping"
)

// WarpClient is the client API for Warp service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WarpClient interface {
	CheckDuplicateTransfer(ctx context.Context, in *LookupName, opts ...grpc.CallOption) (*HaveDuplicate, error)
	GetRemoteMachineInfo(ctx context.Context, in *LookupName, opts ...grpc.CallOption) (*RemoteMachineInfo, error)
	GetRemoteMachineAvatar(ctx context.Context, in *LookupName, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RemoteMachineAvatar], error)
	ProcessTransferOpRequest(ctx context.Context, in *TransferOpRequest, opts ...grpc.CallOption) (*VoidType, error)
	StartTransfer(ctx context.Context, in *OpInfo, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FileChunk], error)
	CancelTransferOpRequest(ctx context.Context, in *OpInfo, opts ...grpc.CallOption) (*VoidType, error)
	StopTransfer(ctx context.Context, in *StopInfo, opts ...grpc.CallOption) (*VoidType, error)
	Ping(ctx context.Context, in *LookupName, opts ...grpc.CallOption) (*VoidType, error)
}

type warpClient struct {
	cc grpc.ClientConnInterface
}

func NewWarpClient(cc grpc.ClientConnInterface) WarpClient {
	return &warpClient{cc}
}

func (c *warpClient) CheckDuplicateTransfer(ctx context.Context, in *LookupName, opts ...grpc.CallOption) (*HaveDuplicate, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HaveDuplicate)
	err := c.cc.Invoke(ctx, Warp_CheckDuplicateTransfer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *warpClient) GetRemoteMachineInfo(ctx context.Context, in *LookupName, opts ...grpc.CallOption) (*RemoteMachineInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoteMachineInfo)
	err := c.cc.Invoke(ctx, Warp_GetRemoteMachineInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *warpClient) GetRemoteMachineAvatar(ctx context.Context, in *LookupName, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RemoteMachineAvatar], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Warp_ServiceDesc.Streams[0], Warp_GetRemoteMachineAvatar_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LookupName, RemoteMachineAvatar]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Warp_GetRemoteMachineAvatarClient = grpc.ServerStreamingClient[RemoteMachineAvatar]

func (c *warpClient) ProcessTransferOpRequest(ctx context.Context, in *TransferOpRequest, opts ...grpc.CallOption) (*VoidType, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VoidType)
	err := c.cc.Invoke(ctx, Warp_ProcessTransferOpRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *warpClient) StartTransfer(ctx context.Context, in *OpInfo, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FileChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Warp_ServiceDesc.Streams[1], Warp_StartTransfer_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[OpInfo, FileChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Warp_StartTransferClient = grpc.ServerStreamingClient[FileChunk]

func (c *warpClient) CancelTransferOpRequest(ctx context.Context, in *OpInfo, opts ...grpc.CallOption) (*VoidType, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VoidType)
	err := c.cc.Invoke(ctx, Warp_CancelTransferOpRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *warpClient) StopTransfer(ctx context.Context, in *StopInfo, opts ...grpc.CallOption) (*VoidType, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VoidType)
	err := c.cc.Invoke(ctx, Warp_StopTransfer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *warpClient) Ping(ctx context.Context, in *LookupName, opts ...grpc.CallOption) (*VoidType, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VoidType)
	err := c.cc.Invoke(ctx, Warp_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WarpServer is the server API for Warp service.
// All implementations must embed UnimplementedWarpServer
// for forward compatibility.
type WarpServer interface {
	CheckDuplicateTransfer(context.Context, *LookupName) (*HaveDuplicate, error)
	GetRemoteMachineInfo(context.Context, *LookupName) (*RemoteMachineInfo, error)
	GetRemoteMachineAvatar(*LookupName, grpc.ServerStreamingServer[RemoteMachineAvatar]) error
	ProcessTransferOpRequest(context.Context, *TransferOpRequest) (*VoidType, error)
	StartTransfer(*OpInfo, grpc.ServerStreamingServer[FileChunk]) error
	CancelTransferOpRequest(context.Context, *OpInfo) (*VoidType, error)
	StopTransfer(context.Context, *StopInfo) (*VoidType, error)
	Ping(context.Context, *LookupName) (*VoidType, error)
	mustEmbedUnimplementedWarpServer()
}

// UnimplementedWarpServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWarpServer struct{}

func (UnimplementedWarpServer) CheckDuplicateTransfer(context.Context, *LookupName) (*HaveDuplicate, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckDuplicateTransfer not implemented")
}
func (UnimplementedWarpServer) GetRemoteMachineInfo(context.Context, *LookupName) (*RemoteMachineInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRemoteMachineInfo not implemented")
}
func (UnimplementedWarpServer) GetRemoteMachineAvatar(*LookupName, grpc.ServerStreamingServer[RemoteMachineAvatar]) error {
	return status.Error(codes.Unimplemented, "method GetRemoteMachineAvatar not implemented")
}
func (UnimplementedWarpServer) ProcessTransferOpRequest(context.Context, *TransferOpRequest) (*VoidType, error) {
	return nil, status.Error(codes.Unimplemented, "method ProcessTransferOpRequest not implemented")
}
func (UnimplementedWarpServer) StartTransfer(*OpInfo, grpc.ServerStreamingServer[FileChunk]) error {
	return status.Error(codes.Unimplemented, "method StartTransfer not implemented")
}
func (UnimplementedWarpServer) CancelTransferOpRequest(context.Context, *OpInfo) (*VoidType, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelTransferOpRequest not implemented")
}
func (UnimplementedWarpServer) StopTransfer(context.Context, *StopInfo) (*VoidType, error) {
	return nil, status.Error(codes.Unimplemented, "method StopTransfer not implemented")
}
func (UnimplementedWarpServer) Ping(context.Context, *LookupName) (*VoidType, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedWarpServer) mustEmbedUnimplementedWarpServer() {}
func (UnimplementedWarpServer) testEmbeddedByValue()              {}

// UnsafeWarpServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WarpServer will
// result in compilation errors.
type UnsafeWarpServer interface {
	mustEmbedUnimplementedWarpServer()
}

func RegisterWarpServer(s grpc.ServiceRegistrar, srv WarpServer) {
	// If the following call panics, it indicates UnimplementedWarpServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Warp_ServiceDesc, srv)
}

func _Warp_CheckDuplicateTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookupName)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarpServer).CheckDuplicateTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Warp_CheckDuplicateTransfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarpServer).CheckDuplicateTransfer(ctx, req.(*LookupName))
	}
	return interceptor(ctx, in, info, handler)
}

func _Warp_GetRemoteMachineInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookupName)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarpServer).GetRemoteMachineInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Warp_GetRemoteMachineInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarpServer).GetRemoteMachineInfo(ctx, req.(*LookupName))
	}
	return interceptor(ctx, in, info, handler)
}

func _Warp_GetRemoteMachineAvatar_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LookupName)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WarpServer).GetRemoteMachineAvatar(m, &grpc.GenericServerStream[LookupName, RemoteMachineAvatar]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Warp_GetRemoteMachineAvatarServer = grpc.ServerStreamingServer[RemoteMachineAvatar]

func _Warp_ProcessTransferOpRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferOpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarpServer).ProcessTransferOpRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Warp_ProcessTransferOpRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarpServer).ProcessTransferOpRequest(ctx, req.(*TransferOpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Warp_StartTransfer_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(OpInfo)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WarpServer).StartTransfer(m, &grpc.GenericServerStream[OpInfo, FileChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Warp_StartTransferServer = grpc.ServerStreamingServer[FileChunk]

func _Warp_CancelTransferOpRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarpServer).CancelTransferOpRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Warp_CancelTransferOpRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarpServer).CancelTransferOpRequest(ctx, req.(*OpInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Warp_StopTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarpServer).StopTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Warp_StopTransfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarpServer).StopTransfer(ctx, req.(*StopInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Warp_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookupName)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarpServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Warp_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarpServer).Ping(ctx, req.(*LookupName))
	}
	return interceptor(ctx, in, info, handler)
}

// Warp_ServiceDesc is the grpc.ServiceDesc for Warp service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Warp_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "warp.Warp",
	HandlerType: (*WarpServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckDuplicateTransfer",
			Handler:    _Warp_CheckDuplicateTransfer_Handler,
		},
		{
			MethodName: "GetRemoteMachineInfo",
			Handler:    _Warp_GetRemoteMachineInfo_Handler,
		},
		{
			MethodName: "ProcessTransferOpRequest",
			Handler:    _Warp_ProcessTransferOpRequest_Handler,
		},
		{
			MethodName: "CancelTransferOpRequest",
			Handler:    _Warp_CancelTransferOpRequest_Handler,
		},
		{
			MethodName: "StopTransfer",
			Handler:    _Warp_StopTransfer_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _Warp_Ping_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetRemoteMachineAvatar",
			Handler:       _Warp_GetRemoteMachineAvatar_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StartTransfer",
			Handler:       _Warp_StartTransfer_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "warp.proto",
}
