// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {sync} from '../models';

export function GetDefaultDownloadPath():Promise<string>;

export function GetTransfers():Promise<Array<main.FileTransfer>>;

export function Len():Promise<number>;

export function Lock():Promise<void>;

export function RLock():Promise<void>;

export function RLocker():Promise<sync.Locker>;

export function RUnlock():Promise<void>;

export function ReceiveFile(arg1:string,arg2:string):Promise<string>;

export function SelectDirectory():Promise<string>;

export function SelectFile():Promise<string>;

export function SendFile(arg1:string):Promise<string>;

export function TryLock():Promise<boolean>;

export function TryRLock():Promise<boolean>;

export function Unlock():Promise<void>;
