// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDefaultDownloadPath() {
  return window['go']['main']['App']['GetDefaultDownloadPath']();
}

export function GetTransfers() {
  return window['go']['main']['App']['GetTransfers']();
}

export function Len() {
  return window['go']['main']['App']['Len']();
}

export function Lock() {
  return window['go']['main']['App']['Lock']();
}

export function RLock() {
  return window['go']['main']['App']['RLock']();
}

export function RLocker() {
  return window['go']['main']['App']['RLocker']();
}

export function RUnlock() {
  return window['go']['main']['App']['RUnlock']();
}

export function ReceiveFile(arg1, arg2) {
  return window['go']['main']['App']['ReceiveFile'](arg1, arg2);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function SendFile(arg1) {
  return window['go']['main']['App']['SendFile'](arg1);
}

export function TryLock() {
  return window['go']['main']['App']['TryLock']();
}

export function TryRLock() {
  return window['go']['main']['App']['TryRLock']();
}

export function Unlock() {
  return window['go']['main']['App']['Unlock']();
}
