// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetTransfers():Promise<Array<main.FileTransfer>>;

export function ReceiveFile(arg1:string,arg2:string):Promise<string>;

export function SelectDirectory():Promise<string>;

export function SelectFile():Promise<string>;

export function SendFile(arg1:string):Promise<string>;
