// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelTransfer(arg1) {
  return window['go']['main']['App']['CancelTransfer'](arg1);
}

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function ConfirmResend(arg1) {
  return window['go']['main']['App']['ConfirmResend'](arg1);
}

export function FirewallNeedsFix() {
  return window['go']['main']['App']['FirewallNeedsFix']();
}

export function FixFirewall() {
  return window['go']['main']['App']['FixFirewall']();
}

export function GetBuildStamp() {
  return window['go']['main']['App']['GetBuildStamp']();
}

export function GetDefaultDownloadPath() {
  return window['go']['main']['App']['GetDefaultDownloadPath']();
}

export function GetDeviceName() {
  return window['go']['main']['App']['GetDeviceName']();
}

export function GetNearbyPeers() {
  return window['go']['main']['App']['GetNearbyPeers']();
}

export function GetNearbyPrefs() {
  return window['go']['main']['App']['GetNearbyPrefs']();
}

export function GetOfflineGuidance() {
  return window['go']['main']['App']['GetOfflineGuidance']();
}

export function GetTransfers() {
  return window['go']['main']['App']['GetTransfers']();
}

export function ReceiveFile(arg1, arg2) {
  return window['go']['main']['App']['ReceiveFile'](arg1, arg2);
}

export function ResendTransfer(arg1) {
  return window['go']['main']['App']['ResendTransfer'](arg1);
}

export function RespondToNearbyOffer(arg1, arg2) {
  return window['go']['main']['App']['RespondToNearbyOffer'](arg1, arg2);
}

export function RespondToOverwrite(arg1, arg2) {
  return window['go']['main']['App']['RespondToOverwrite'](arg1, arg2);
}

export function RevealInExplorer(arg1) {
  return window['go']['main']['App']['RevealInExplorer'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function SelectFiles() {
  return window['go']['main']['App']['SelectFiles']();
}

export function SendFile(arg1) {
  return window['go']['main']['App']['SendFile'](arg1);
}

export function SendFiles(arg1) {
  return window['go']['main']['App']['SendFiles'](arg1);
}

export function SendToPeer(arg1, arg2) {
  return window['go']['main']['App']['SendToPeer'](arg1, arg2);
}

export function SetNearbyVisible(arg1) {
  return window['go']['main']['App']['SetNearbyVisible'](arg1);
}

export function StartPhoneReceive() {
  return window['go']['main']['App']['StartPhoneReceive']();
}

export function StopPhoneReceive() {
  return window['go']['main']['App']['StopPhoneReceive']();
}
