// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetTransfers() {
  return window['go']['main']['App']['GetTransfers']();
}

export function ReceiveFile(arg1, arg2) {
  return window['go']['main']['App']['ReceiveFile'](arg1, arg2);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function SendFile(arg1) {
  return window['go']['main']['App']['SendFile'](arg1);
}
