// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelTransfer(arg1:string):Promise<void>;

export function ClearHistory():Promise<void>;

export function ConfirmResend(arg1:string):Promise<main.ResendOutcome>;

export function FirewallNeedsFix():Promise<boolean>;

export function FixFirewall():Promise<void>;

export function GetBuildStamp():Promise<string>;

export function GetDefaultDownloadPath():Promise<string>;

export function GetDeviceName():Promise<string>;

export function GetNearbyPeers():Promise<Array<main.NearbyPeer>>;

export function GetNearbyPrefs():Promise<main.NearbyPrefs>;

export function GetOfflineGuidance():Promise<main.OfflineGuidance>;

export function GetTransfers():Promise<Array<main.FileTransfer>>;

export function ReceiveFile(arg1:string,arg2:string):Promise<string>;

export function ResendTransfer(arg1:string):Promise<main.ResendOutcome>;

export function RespondToNearbyOffer(arg1:string,arg2:boolean):Promise<void>;

export function RespondToOverwrite(arg1:string,arg2:string):Promise<void>;

export function RevealInExplorer(arg1:string):Promise<void>;

export function SelectDirectory():Promise<string>;

export function SelectFile():Promise<string>;

export function SelectFiles():Promise<Array<string>>;

export function SendFile(arg1:string):Promise<string>;

export function SendFiles(arg1:Array<string>):Promise<string>;

export function SendToPeer(arg1:string,arg2:Array<string>):Promise<string>;

export function SetNearbyVisible(arg1:boolean):Promise<void>;

export function StartPhoneReceive():Promise<main.PhoneReceiveInfo>;

export function StopPhoneReceive():Promise<void>;
