name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc libgtk-3-dev libwebkit2gtk-4.1-dev
          
      - name: Install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest
        
      - name: Install dependencies
        run: |
          cd frontend
          npm install
          
      - name: Build Linux application
        run: wails build -tags webkit2_41 -o krokodyl
        
      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: krokodyl-linux
          path: build/bin/krokodyl

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest
        
      - name: Install dependencies
        run: |
          cd frontend
          npm install
          
      - name: Build Windows application
        run: wails build -platform windows/amd64 -o krokodyl.exe
        
      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: krokodyl-windows
          path: build/bin/krokodyl.exe

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest
        
      - name: Install dependencies
        run: |
          cd frontend
          npm install
          
      - name: Build macOS application
        run: wails build -platform darwin/amd64 -o krokodyl
        
      - name: Extract macOS executable from app bundle
        run: |
          if [ -d "build/bin/krokodyl.app" ]; then
            cp build/bin/krokodyl.app/Contents/MacOS/krokodyl build/bin/krokodyl-executable
          else
            cp build/bin/krokodyl build/bin/krokodyl-executable
          fi
        
      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: krokodyl-macos
          path: build/bin/krokodyl-executable

  release:
    needs: [build-linux, build-windows, build-macos]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Download Linux artifact
        uses: actions/download-artifact@v4
        with:
          name: krokodyl-linux
          path: ./artifacts/linux/
          
      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: krokodyl-windows
          path: ./artifacts/windows/
          
      - name: Download macOS artifact
        uses: actions/download-artifact@v4
        with:
          name: krokodyl-macos
          path: ./artifacts/macos/
          
      - name: Rename artifacts
        run: |
          mv artifacts/linux/krokodyl artifacts/krokodyl-linux
          mv artifacts/windows/krokodyl.exe artifacts/krokodyl-windows.exe
          mv artifacts/macos/krokodyl-executable artifacts/krokodyl-macos
          
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/krokodyl-linux
            artifacts/krokodyl-windows.exe
            artifacts/krokodyl-macos
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}